runtime: nodejs16

env_variables:
  NODE_ENV: production

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 100

handlers:
  - url: /.*
    script: auto
